
import Homepage from "@/src/components/Homepage";
import Timeline from "@/src/components/Timeline";
import Head from "next/head";


export default function Home() {
 return (
  <>
  <Head>
    <title>SNS APP</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <div>
    <Timeline />
    <Homepage />
    </div>
  </>
  );
}
